name: 'CDKTF Deploy'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: 'CDKTF Deploy'
    concurrency:
      group: cdktf-deploy
      cancel-in-progress: false
    uses: BNGUYENLAB/rdm-pipeline-templates/.github/workflows/hz_apply_template.yml@main
    with:
      aws-role: "arn:aws:iam::849864070883:role/github_actions_admin_ducloi_local"
      runner_label: small
      aws-region: ap-southeast-1
